### ISSUE TITLE
GPTSimpleVectorIndex( documents) line ERROR ...

### ISSUE THREAD

**Issue by styang90** [timothymugayi/mychatbot#1]
When executing follow line:
index = GPTSimpleVectorIndex( documents)

There is a error:
ValueError: The constructor now takes in a list of Node objects. Since you are passing in a list of Document objects, please use `from_documents` instead.

**Comment by edengbigabid** [comment]
The error is self-explanatory. 
Use GPTSimpleVectorIndex.from_documents.

**Comment by timothymugayi** [comment]
Please see the package versions being used and use the environment.yml to create your virtual env so code works as expected. Langchain and LlamaIndex are been updated daily 

https://github.com/timothymugayi/mychatbot/blob/main/environment.yml
